"""
NSE F&O Stock Universe (210+ Active Equity Derivative Underlyings)
Excluded: Broad market indices (NIFTY, BANKNIFTY, FINNIFTY, MIDCPNIFTY)
"""

NSE_FNO_SYMBOLS = {
    # Nifty 50 & Heavyweights
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "ITC", "SBIN",
    "BHARTIARTL", "KOTAKBANK", "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "BAJFINANCE",
    "HCLTECH", "SUNPHARMA", "TITAN", "TATAMOTORS", "ULTRACEMCO", "NTPC", "POWERGRID",
    "TATASTEEL", "M&M", "JSWSTEEL", "ADANIENT", "ADANIPORTS", "COALINDIA", "BAJAJFINSV",
    "GRASIM", "TECHM", "NESTLEIND", "CIPLA", "WIPRO", "ONGC", "HINDALCO", "DIVISLAB",
    "BPCL", "EICHERMOT", "BRITANNIA", "APOLLOHOSP", "TATACONSUM", "DRREDDY", "SBILIFE",
    "HEROMOTOCO", "SHRIRAMFIN", "BAJAJ-AUTO", "LTIM", "BEL", "INDUSINDBK",

    # Nifty Next 50 & High Beta F&O Equities
    "ABB", "ACC", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "ASHOKLEY", "ASTRAL", "AUBANK",
    "AUROPHARMA", "BALKRISIND", "BANDHANBNK", "BANKBARODA", "BATAINDIA", "BERGEPAINT",
    "BHARATFORG", "BHEL", "BIOCON", "BOSCHLTD", "CANBK", "CANFINHOME", "CHAMBLFERT",
    "CHOLAFIN", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "CROMPTON", "CUB",
    "CUMMINSIND", "DABUR", "DALBHARAT", "DEEPAKNTR", "DELHIVERY", "DIVISLAB", "DIXON",
    "DLF", "ESCORTS", "EXIDEIND", "FEDERALBNK", "GAIL", "GLENMARK", "GMRINFRA",
    "GNFC", "GODREJCP", "GODREJPROP", "GRANULES", "GUJGASLTD", "HAL", "HAVELLS",
    "HDFCAMC", "HDFCLIFE", "HINDCOPPER", "HINDPETRO", "HONAUT", "ICICIGI", "ICICIPRULI",
    "IDEA", "IDFC", "IDFCFIRSTB", "IEX", "IGL", "INDHOTEL", "INDIACEM", "INDIAMART",
    "INDIGO", "INDUSTOWER", "IOC", "IPCALAB", "IRCTC", "JINDALSTEL", "JKCEMENT",
    "JSL", "JUBLFOOD", "KALYANKJIL", "L&TFH", "LALPATHLAB", "LAURUSLABS", "LICHSGFIN",
    "LUPIN", "M&MFIN", "MANAPPURAM", "MARICO", "MCX", "METROPOLIS", "MFSL", "MGL",
    "MOTHERSON", "MPHASIS", "MRF", "MUTHOOTFIN", "NATIONALUM", "NAVINFLUOR", "NAUKRI",
    "NMDC", "OBEROIRLTY", "OFSS", "PAGEIND", "PEL", "PERSISTENT", "PETRONET", "PFC",
    "PIDILITIND", "PIIND", "PNB", "POLICYBZR", "POLYCAB", "POONAWALLA", "PRESTIGE",
    "PVRINOX", "RAMCOCEM", "RBLBANK", "RECLTD", "SAIL", "SBICARD", "SIEMENS", "SRF",
    "SUNTV", "SYNGENE", "TATACHEM", "TATACOMM", "TATAPOWER", "TRENT", "TVSMOTOR",
    "UBL", "UNITDSPR", "UPL", "VBL", "VEDL", "VOLTAS", "ZEEL", "ZYDUSLIFE",

    # Midcap Momentum & Liquid Derivatives
    "ABCAPITAL", "ANGELONE", "APOLLOTYRE", "ATUL", "BSOFT", "CDSL", "CESC",
    "CHAMBLFERT", "CLEAN", "COOCHINSHIP", "COROMANDEL", "CREDITACC", "CYIENT",
    "DEVYANI", "FACT", "FSL", "GLS", "GNFC", "GODREJIND", "GRINDWELL", "GSPL",
    "HUDCO", "IDBI", "IIFL", "IRFC", "J&KBANK", "JBCHEPHARM", "KEC", "KPITTECH",
    "LEMONTREE", "MAHABANK", "MAXHEALTH", "MAZDOCK", "METROBRAND", "NATCOPHARM",
    "NBCC", "NHPC", "NLCINDIA", "OIL", "PATANJALI", "PAYTM", "PPLPHARMA",
    "RADICO", "RAILTEL", "RATNAMANI", "RITES", "RVNL", "SJVN", "SONACOMS",
    "SUNDARMFIN", "SUPREMEIND", "SUZLON", "SWANENERGY", "TARSONS", "TIINDIA",
    "TRITURBINE", "UCOBANK", "UNIONBANK", "VAIBHAVGBL", "VIJAYA", "ZOMATO"
}

def is_valid_fno_symbol(symbol: str) -> bool:
    """Validates whether a given symbol exists in the 210+ NSE F&O universe."""
    clean = symbol.strip().upper().replace("NSE:", "").replace("&", "")
    return clean in NSE_FNO_SYMBOLS or symbol.strip().upper() in NSE_FNO_SYMBOLS
